### ISSUE TITLE
[minor] How to get rid of XText conversion proposal?

### ISSUE THREAD

**Issue by paulvi** [itemis/jbc#6]
How to get rid of initial XText conversion proposal?

![image](https://user-images.githubusercontent.com/1614482/35332903-c09ea550-0147-11e8-9f1b-d2eb17a696b3.png)

**Comment by kthoms** [comment]
This can't be deactived. It will just add the Xtext nature and the builder to the project, which is mandatory to have Xtext editor support. The message comes up when Xtext recognizes that a file with a file extension for an installed language is opened. It is not a good option to silently do this since it could degrade performance on large workspaces unintendently.

**Comment by paulvi** [comment]
> It will just add the Xtext nature and the builder to the project, which is mandatory

I opted out, and the plugin worked. So it is not mandatory.  
Or could some features be unavailable?

**Comment by kthoms** [comment]
It may work for this special editor, but it would disable Xtext's builder and for regular languages this would just not work. Features like cross referencing across files can only work with the builder enabled.

**Comment by ArneDeutsch** [comment]
From my point of view the dialog is questionable. I understand why it is there. Probably in a future xtext version one can introduce a method in the XtextEditor to opt-out from the dialog. Then the JBC editor can avoid to open the dialog. But for current version there is no such method. For now I have to live with the dialog. Saying "No" is perfectly ok, the editor does not require the nature.

**Comment by ArneDeutsch** [comment]
Fixed with v1.2.2
